import pkgutil
INPUT = pkgutil.get_data('solution', 'input').decode()

EXAMPLE=""".......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............
"""


def part1(inpt):
    return 0

def part2(inpt):
    return 0

if __name__ == "__main__":
    print()
    assert part1(EXAMPLE) == 21
    assert part2(EXAMPLE) == 0
    print(part1(INPUT))
    print(part2(INPUT))
